account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='account'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('like_more/<int:pk>/', views.LikeMoreView, name='like_more'),
]

game/urls.py
from django.urls import path

from game.views import GameCreateView, GameUpdateView, GameDetailView, GameListView, GameSearchView, \
    update_like, deleteGame

from game.views import GameSearchFilter

app_name='game'

urlpatterns = [
    path('create/', GameCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GameUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', GameDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', deleteGame, name='delete'),

    path('list/', GameListView.as_view(), name='list'),
    path('search/', GameSearchFilter.as_view(), name='search_filter'),
    path('search/<str:q>/', GameSearchView.as_view(), name='search'),
    path('like/', update_like, name='like')\

]

gameplaylist/urls.py
from django.urls import path


from gameplaylist.views import GamePlaylistCreateView, deleteGameplaylist, GamePlaylistListView, GamePlaylistDetailView, \
    addOrRemoveGame, removeGame, collectGamePlaylist, GamePlaylistUpdateView

app_name='gameplaylist'

urlpatterns = [
    path('create/', GamePlaylistCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GamePlaylistUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', GamePlaylistDetailView.as_view(), name='detail'),
    path('detail/<int:pk>/delete/', deleteGameplaylist, name='delete'),
    path('list/delete/<int:pk>/', deleteGameplaylist, name='delete'),
    path('list/', GamePlaylistListView.as_view(), name='list'),

    path('detail/<int:pk>/collect/', collectGamePlaylist, name='collect'),

    path('add_or_remove_game/', addOrRemoveGame, name='add_or_remove_game'),
    path('detail/<int:pk1>/remove_game/<int:pk2>/', removeGame, name='remove_game'),

]

hamgame/hamgame/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', views.index, name='index'),
    path('pybo/', include('pybo.urls'))
]

single_pages/urls.py
from django.urls import path

from single_pages.views import mainPage, LikedRankingPage, SituationRankingPage, myPage

app_name='page'

urlpatterns = [
    path('', mainPage, name='main'),
    path('ranking/liked/', LikedRankingPage, name='likedRanking'),
    path('ranking/situation/<int:pk>', SituationRankingPage, name='situationRanking'),
    path('mypage/<int:pk>/', myPage, name='mypage'),

]

togethergame/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('games/', include('game.urls')),
    path('gameplaylists/', include('gameplaylist.urls')),
    path('accounts/', include('account.urls')),
    path('', include('single_pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

single_pages/models.py
from django.db import models

# Create your models here.

single_pages/views.py
from datetime import datetime, timedelta

from django.db.models import Count
from django.shortcuts import render

# Create your views here.
from account.models import User
from game.models import Game, Situation

situations_str = ['술게임', 'MT']

# 메인페이지
def mainPage(request):
    one_month_ago = datetime.now() - timedelta(days=30)
    liked_ranking = Game.objects.filter(likes__created_at__gte=one_month_ago) \
                    .annotate(like_count=Count('likes')).order_by('-like_count')[:4]

    situations_list = []
    for s in situations_str:
        list = Game.objects.filter(situation_id=Situation.objects.get(name=s).pk) \
                .annotate(like_count=Count('likes')).order_by('-like_count')[:4]
        situations_list.append(list)

    return render(request, 'single_pages/main.html', {
        'liked_ranking': liked_ranking,
        'situation_ranking1': situations_list[0],
        'situation_ranking2': situations_list[1],
        'list': situations_str
    })

# 좋아요 랭킹 페이지
def LikedRankingPage(request):
    one_month_ago = datetime.now() - timedelta(days=30)
    liked_ranking = Game.objects.filter(likes__created_at__gte=one_month_ago) \
                    .annotate(like_count=Count('likes')).order_by('-like_count')[:10]
    return render(request, 'single_pages/ranking.html', {
        'title': '최근 인기',
        'liked_ranking': liked_ranking,
    })

# 상황별 랭킹 페이지
def SituationRankingPage(request, pk):
    situation_ranking = Game.objects.filter(situation_id=Situation.objects.get(name=situations_str[pk]).pk) \
                    .annotate(like_count=Count('likes')).order_by('-like_count')[:10]
    return render(request, 'single_pages/ranking.html', {
        'title': '상황별 랭킹',
        'situation': situations_str[pk],
        'situation_ranking': situation_ranking,
    })

# 마이페이지
def myPage(request, pk):
    user = User.objects.get(pk=pk)
    liked_list = Game.objects.filter(likes__in=user.like.all())
    like_count = liked_list.count
    liked_list = liked_list[::-1]
    liked_list = liked_list[:2]
    collected_list = user.collected_gamelist.all()
    collect_count = user.collected_gamelist.count
    collected_list = collected_list[::-1]
    collected_list = collected_list[:2]

    return render(request, 'single_pages/mypage.html', {
        'target_user':user,
        'liked_list':liked_list,
        'like_count':like_count,
        'collected_list': collected_list,
        'collect_count':collect_count
    })

single_pages/templates/single_pages/main.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/main.css' %}?after" />
{% endblock %}



{% block content %}

    <div class="img_wrapper" >
        <p>최근 인기</p>
        <h3><a href="{% url 'page:likedRanking' %}" role="button">최근 인기 게임 > </a></h3>
        <ul class="img_list">
            {% for game in liked_ranking %}
                {% include 'snippets/game_part.html' with game=game %}
            {% endfor %}
        </ul>
    </div>

<div class="img_wrapper" >
    <p>상황 별 게임</p>
    <h3><a href="{% url 'page:situationRanking' pk=0 %}">술자리 게임 > </a></h3>
    <ul class="img_list">
        {% for game in situation_ranking1 %}
            {% include 'snippets/game_part.html' with game=game %}
        {% endfor %}
    </ul>
</div>

<div class="img_wrapper" >
    <h3><a href="{% url 'page:situationRanking' pk=1 %}">MT > </a></h3>
    <ul class="img_list">
        {% for game in situation_ranking2 %}
        {% include 'snippets/game_part.html' with game=game %}
        {% endfor %}
    </ul>
</div>

{% endblock %}

single_pages/templates/single_pages/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/mypage.css' %}?after" />
{% endblock %}

{% block content %}
<div class="container">
  <div class="mypage-info">
    <h2>{{ target_user.nickname }}님, 안녕하세요!</h2>
    <a href="#">내 정보 수정 ></a>
    <a href="#">내가 쓴 글 목록 ></a>
  </div>
    <div class="my-game" >
      <div class="like-game">
        <div class="like-game-title">
          <img src="{% static 'img/blacklike.png' %}" alt="" />
            <a href="{% url 'account:like_more' pk=user.pk%}"><span>좋아요한 게임</span></a>
            <span>{{ like_count }}</span>
        </div>
        <ul>
        {% for game in liked_list %}
          {% include 'snippets/mypage_game_part.html' %}
        {% endfor %}
        </ul>
      </div>

      <div class="save-game">
        <div class="like-game-title">
          <img src="{% static 'img/folder.png' %}" alt="" />
          <a href="{% url 'gameplaylist:list' %}"><span>담은 게임</span></a>
          <span>{{ collect_count }}</span>
        </div>
        <ul>
            {% for game in collected_list %}
                <a href="{% url 'gameplaylist:detail' pk=game.pk%}">
                    <li>
                        {% if game.image %}
                        <img src="{{ game.image.url }}" width="100px" height="100px" alt="">
                        {% else %}
                        <img src="{% static 'img/thumbnail.png' %}" alt="">
                        {% endif %}

                        <div class="like-game-element">
                            <div class="about-game">
                                <h4>{{game.title | truncatechars:45 }}</h4>
                                <p>{{ game.created_at | date:'Y.m.d' }}</p>
                            </div>

                        </div>
                    </li>
                </a>
            {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

single_pages/templates/single_pages/ranking.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/main_alcohol.css' %}?after" />
{% endblock %}
{% load static %}

{% block content %}

  <!-- 최근 인기 게임 div -->
{% if liked_ranking %}
<div class="container">
  <div class="sec1">
    <p>{{ title }}</p>
  </div>
  <div class="sec2">
    <ul>
      {% for game in liked_ranking %}
        {% include 'snippets/ranking_game_part.html' with game=game %}
      {% endfor %}
    </ul>
  </div>
</div>
    {% endif %}

{% if situation_ranking %}
<div class="container">
  <div class="sec1">
    <p>{{ situation }}</p>
  </div>
  <div class="sec2">
    <ul>
      {% for game in situation_ranking %}
        {% include 'snippets/ranking_game_part.html' with game=game %}
      {% endfor %}
    </ul>
  </div>
</div>
    {% endif %}



<script>
  // JavaScript 코드
document.addEventListener("DOMContentLoaded", function() {
  const likeIcons = document.querySelectorAll(".like-icon");

  likeIcons.forEach(icon => {
    icon.addEventListener("click", function() {
      // 이미지를 토글하여 표시하거나 숨김
      icon.classList.toggle("active");

      // 토글된 상태에 따라 다른 이미지 표시
      if (icon.classList.contains("active")) {
        icon.src = "{% static 'img/likefull.png' %}";
      } else {
        icon.src = "{% static 'img/like.png' %}";
      }
    });
  });
});
</script>

{% endblock %}