account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='account'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('like_more/<int:pk>/', views.LikeMoreView, name='like_more'),
]

game/urls.py
from django.urls import path

from game.views import GameCreateView, GameUpdateView, GameDetailView, GameListView, GameSearchView, \
    update_like, deleteGame

from game.views import GameSearchFilter

app_name='game'

urlpatterns = [
    path('create/', GameCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GameUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', GameDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', deleteGame, name='delete'),

    path('list/', GameListView.as_view(), name='list'),
    path('search/', GameSearchFilter.as_view(), name='search_filter'),
    path('search/<str:q>/', GameSearchView.as_view(), name='search'),
    path('like/', update_like, name='like')\

]

hamgame/hamgame/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', views.index, name='index'),
    path('pybo/', include('pybo.urls'))
]

single_pages/urls.py
from django.urls import path

from single_pages.views import mainPage, LikedRankingPage, SituationRankingPage, myPage

app_name='page'

urlpatterns = [
    path('', mainPage, name='main'),
    path('ranking/liked/', LikedRankingPage, name='likedRanking'),
    path('ranking/situation/<int:pk>', SituationRankingPage, name='situationRanking'),
    path('mypage/<int:pk>/', myPage, name='mypage'),

]

togethergame/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('games/', include('game.urls')),
    path('gameplaylists/', include('gameplaylist.urls')),
    path('accounts/', include('account.urls')),
    path('', include('single_pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>함께임</title>
    {% block extrahead %}
    {% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@500&display=swap" rel="stylesheet">
</head>

<body>
    {% include 'nav.html' %}

    {% block content %}

    {% endblock %}



</body>


</html>

templates/footer.html
    <div class="pragmatic_footer"> <!-- margin: 상하 좌우 -->
        <div class="pragmatic_footer_button">
            <span>공지사항</span> |
            <span>제휴문의</span> |
            <span>서비스 소개</span>
        </div>
        <div style="margin-top: 1rem;">
            <h6 class="pragmatic_logo">Pragmatic</h6>
        </div>
    </div>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
        {% if field.errors %}
        <div>
            <h6>{{ field.label }}</h6>
            <h6>{{ field.errors }}</h6>
        </div>
        {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <h6>{{ error }}</h6>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>함께임</title>
    {% block extrahead %}
    {% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@700&display=swap" rel="stylesheet">
</head>

templates/header.html
    <div class="togethergame_header">
         <div>
             <h1 class="togethergame_logo">togetherGame</h1>
         </div>
         <div>
             <a href="{% url 'page:main' %}">
                <span>인기 게임</span>
             </a>
             <a href="{% url 'game:list' %}">
                <span>게임 목록</span>
             </a>
             <a href="{% url 'game:create' %}">
                <span>게임 등록</span>
             </a>
            {% if not user.is_authenticated %}
             <a href="{% url 'account:login' %}?next={% url 'game:list' %}">
                <span>login</span>
             </a>
             <a href="{% url 'account:create' %} ">
                <span>SignUp</span>
             </a>
             {% else %}
             <a href="{% url 'page:mypage' pk=user.pk%}">
                <span>MyPage</span>
             </a>
             <a href="{% url 'account:logout' %}?next={% url 'game:list' %}">
                <span>logout</span>
             </a>
             {% endif %}
         </div>
        <div class="input-group">
            <input id="search-input" class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
            <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost()">Go!</button>
        </div>
        <script>
            function searchPost(){
                let searchValue = document.getElementById('search-input').value.trim();
                if(searchValue.length > 1){
                    location.href = "/games/search/"+searchValue+"/";
                }
                else{
                    alert('검색어('+searchValue+')가 너무 짧습니다.');
                }
            };
            document.getElementById('search-input').addEventListener('keyup',function(event){
                if(event.key === 'Enter'){
                    searchPost();
                }
            });
        </script>
    </div>

templates/nav.html
{% load static %}
<div class="nav-wrapper">
    <a href="{% url 'page:main' %}"><img src="{% static 'img/title.png' %}" alt="타이틀" /></a>
    <div class="search">
        <input id="search-input" class="form-control" type="text" placeholder="검색어를 입력하세요" aria-label="Enter search term..." aria-describedby="button-search" />
        <button onclick="searchPost()">
            <img src="{% static 'img/serch.png' %}" alt="검색" />

        </button>
    </div>
</div>
<nav>
    <ul class="nav-list">
        <li class="bold"><a href="{% url 'page:main' %}">인기 게임</a></li>
        <li><a href="{% url 'game:list' %}">게임 목록</a></li>
        <li><a href="{% url 'game:create' %}" id="game_create" >게임 등록</a></li>
        {# <li><a href="{% url game:mypage' %}">마이페이지</a></li> #}
        </ul>

        <ul class="nav-list">
            {% if not user.is_authenticated %}
            <li>
              <a href="{% url 'account:signup' %} ">회원 가입</a>
            </li>
            <li>
                <a href="{% url 'account:login' %}">로그인</a>
            </li>
            {% else %}
            <li><a href="{% url 'page:mypage' pk=user.pk%}"><span>마이페이지</span></a></li>
            <li>
                <a href="{% url 'account:logout' %}"><span>로그아웃</span></a>
            </li>
            {% endif %}
        </ul>
    </nav>
<hr />

<script>
    function searchPost(){
        let searchValue = document.getElementById('search-input').value.trim();
        if(searchValue.length > 1){
                    location.href = "/games/search/"+searchValue+"/";
        }
        else{
            alert('검색어('+searchValue+')가 너무 짧습니다.');
        }
    };
    document.getElementById('search-input').addEventListener('keyup',function(event){
        if(event.key === 'Enter'){
            searchPost();
        }
    });

    document.getElementById('game_create').addEventListener('click',function(event){
        {% if not user.is_authenticated %}
            alert("로그인을 해주세요");
            this.href = "{% url 'account:login' %}";
        {% endif %}
    });
</script>