account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='account'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('like_more/<int:pk>/', views.LikeMoreView, name='like_more'),
]

game/urls.py
from django.urls import path

from game.views import GameCreateView, GameUpdateView, GameDetailView, GameListView, GameSearchView, \
    update_like, deleteGame

from game.views import GameSearchFilter

app_name='game'

urlpatterns = [
    path('create/', GameCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GameUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', GameDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', deleteGame, name='delete'),

    path('list/', GameListView.as_view(), name='list'),
    path('search/', GameSearchFilter.as_view(), name='search_filter'),
    path('search/<str:q>/', GameSearchView.as_view(), name='search'),
    path('like/', update_like, name='like')\

]

gameplaylist/urls.py
from django.urls import path


from gameplaylist.views import GamePlaylistCreateView, deleteGameplaylist, GamePlaylistListView, GamePlaylistDetailView, \
    addOrRemoveGame, removeGame, collectGamePlaylist, GamePlaylistUpdateView

app_name='gameplaylist'

urlpatterns = [
    path('create/', GamePlaylistCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GamePlaylistUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', GamePlaylistDetailView.as_view(), name='detail'),
    path('detail/<int:pk>/delete/', deleteGameplaylist, name='delete'),
    path('list/delete/<int:pk>/', deleteGameplaylist, name='delete'),
    path('list/', GamePlaylistListView.as_view(), name='list'),

    path('detail/<int:pk>/collect/', collectGamePlaylist, name='collect'),

    path('add_or_remove_game/', addOrRemoveGame, name='add_or_remove_game'),
    path('detail/<int:pk1>/remove_game/<int:pk2>/', removeGame, name='remove_game'),

]

hamgame/hamgame/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', views.index, name='index'),
    path('pybo/', include('pybo.urls'))
]

togethergame/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('games/', include('game.urls')),
    path('gameplaylists/', include('gameplaylist.urls')),
    path('accounts/', include('account.urls')),
    path('', include('single_pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/models.py
from django.db import models

# Create your models here.
from account.models import User

class Situation(models.Model):
    name = models.CharField(max_length=30, unique=True)
    def __str__(self):
        return f'{self.name}'

class Place(models.Model):
    name = models.CharField(max_length=30, unique=True)
    def __str__(self):
        return f'{self.name}'

class GameType(models.Model):
    name = models.CharField(max_length=30, unique=True)
    def __str__(self):
        return f'{self.name}'


class Game(models.Model):
    title = models.CharField(max_length=30, null=False)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='game')
    created_at = models.DateField(auto_now_add=True)
    #modified_at = models.DateTimeField(auto_now=True)

    min_num_ppl = models.IntegerField(null=True)
    max_num_ppl = models.IntegerField(null=True)
    min_time = models.CharField(max_length=30, null=True)
    max_time = models.CharField(max_length=30, null=True)
    situation = models.ForeignKey(Situation, null=False, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, null=False, on_delete=models.CASCADE)
    game_type = models.ManyToManyField(GameType)

    preparation = models.TextField(null=False)
    explanation = models.TextField(null=False)
    tip = models.TextField()

    image = models.ImageField(upload_to="images/games/", null=True, blank=True)
    likes = models.ManyToManyField('Like', related_name='game', null=True, blank=True)

    def __str__(self):
        return f'{self.title}'

    def likes_count(self):
        return self.likes.count()


class Like(models.Model):
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE, related_name='like')
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}'

game/forms.py
from django import forms

from game.models import Game


class GameCreationForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['title','min_num_ppl', 'max_num_ppl','min_time', 'max_time',
                  'preparation', 'explanation', 'tip', 'image']

game/views.py
from django.db.models import Q, Count
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from game.forms import GameCreationForm
from game.models import Game, Place, Situation, GameType, Like

from gameplaylist.models import GamePlaylist


# 게임 등록
class GameCreateView(CreateView):
    model = Game
    context_object_name = 'target_game'
    form_class = GameCreationForm
    template_name = 'game/create.html'

    def form_valid(self, form):
        temp_game = form.save(commit=False)
        temp_game.author = self.request.user
        temp_game.place = Place.objects.get(name=self.request.POST['place_str'])
        temp_game.situation = Situation.objects.get(name=self.request.POST['situation_str'])
        temp_game.save()
        game_type = self.request.POST.get('game_type_str')
        if game_type:
            tag_list = game_type.strip().replace(',', ';').split(';')
            for t in tag_list:
                t = t.strip()
                if t == '':
                    continue
                tag = GameType.objects.get(name=t)
                temp_game.game_type.add(tag)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('game:detail', kwargs={'pk':self.object.pk})

# 게임 수정
class GameUpdateView(UpdateView):
    model = Game
    context_object_name = 'target_game'
    form_class = GameCreationForm
    template_name = 'game/update.html'

    def form_valid(self, form):
        temp_game = form.save(commit=False)
        temp_game.place = Place.objects.get(name=self.request.POST['place_str'])
        temp_game.situation = Situation.objects.get(name=self.request.POST['situation_str'])
        temp_game.save()
        temp_game.game_type.clear()
        game_type = self.request.POST.get('game_type_str')
        if game_type:
            tag_list = game_type.strip().replace(',', ';').split(';')
            for t in tag_list:
                t = t.strip()
                if t == '':
                    continue
                tag = GameType.objects.get(name=t)
                temp_game.game_type.add(tag)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('game:detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GameUpdateView, self).get_context_data()
        game = Game.objects.get(pk=self.kwargs['pk'])
        context['place'] = game.place.name
        context['situation'] = game.situation.name
        context['game_type'] = game.game_type.all()[0].name
        return context

# # 게임 삭제
# class GameDeleteView(DeleteView):
#     model = Game
#     context_object_name = 'target_game'
#     success_url = reverse_lazy('game:list')
#     template_name = 'game/delete.html'

def deleteGame(request, pk):
    if request.user.is_authenticated:
        game = Game.objects.get(pk=pk)
        if request.user == game.author:
            game.delete()
        return redirect('game:list')

# 게임 목록
class GameListView(ListView):
    model = Game
    context_object_name = 'game_list'
    template_name = 'game/list.html'
    ordering = '-pk'

# 게임 제목 검색
class GameSearchView(GameListView):
    paginate_by = None
    def get_queryset(self):
        q = self.kwargs['q']
        game_list = Game.objects.filter(Q(title__contains=q))#.order_by('-pk')
        game_list = game_list.order_by('-pk')
        return game_list

# 게임 필터 검색
class GameSearchFilter(GameListView):
    paginate_by = None
    def get_queryset(self):
        game_list = None
        q = Q()

        situation = self.request.GET.get('situation_str', False)
        if situation:
            q &= Q(situation_id=Situation.objects.get(name=situation).pk)

        place = self.request.GET.get('place_str', False)
        if place:
            q &= Q(place_id=Place.objects.get(name=place).pk)

        game_type = self.request.GET.get('game_type_str', False)
        if game_type:
            game_type = game_type.split(';')
            if '' in game_type:
                game_type.remove('')
            for i in range(len(game_type)):
               game_type[i] = GameType.objects.get(name=game_type[i])
            q &= Q(game_type__in=game_type)

        sort = self.request.GET.get('sort')
        if sort=="recent":
            game_list = Game.objects.filter(q).distinct().order_by('-pk')
        elif sort=="like":
            game_list = Game.objects.filter(q).distinct().annotate(like_count=Count('likes')).order_by('-like_count')
        return game_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GameSearchFilter, self).get_context_data()
        context['place'] = self.request.GET.get('place_str', False)
        context['situation'] = self.request.GET.get('situation_str', False)
        context['game_type'] = self.request.GET.get('game_type_str', False)
        context['sort'] = self.request.GET.get('sort', False)
        return context

# 게임 상세
class GameDetailView(DetailView):
    model = Game
    context_object_name = 'target_game'
    template_name = 'game/detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GameDetailView, self).get_context_data()
        if self.request.user.is_authenticated:
            game = Game.objects.get(pk=self.object.pk)
            liked_by_user = game.likes.filter(user=self.request.user).exists()
            context['is_like'] = liked_by_user

            context['gameplaylists'] = GamePlaylist.objects.filter(author=self.request.user)
            context['checked_gameplaylists'] = GamePlaylist.objects.filter(Q(author=self.request.user) & Q(games=game)).distinct()
        else:
            context['is_like'] = False
        return context


# 게임 좋아요 추가/삭제
def update_like(request):
    if not request.user.is_authenticated:
        return JsonResponse({'success': False, 'error': '로그인을 해주세요.'})
    else:
        game_pk = request.POST.get('game_id')
        try:
            game = Game.objects.get(pk=game_pk)
        except Game.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Post not found'})

        user_likes = Like.objects.filter(user=request.user, game=game)

        if user_likes.exists(): # 이미 좋아요를 누른 경우, 좋아요 삭제
            user_likes.delete()
            liked = False
        else:   # 좋아요 추가
            like = Like.objects.create(user=request.user)
            liked = True
            game.likes.add(like)  # 다대다 관계 필드에 사용자 추가

        like_count = game.likes.count()

        return JsonResponse({'success': True, 'liked': liked, 'like_count': like_count})

game/templates/game/create.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/add_game.css' %}?after" />
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
      <div class="container">
          <div class="sec1">
            <h2>게임 특징</h2>
            <div class="background">
              <div class="select-name">
                <span>참여 인원</span>
                <span>소요 시간</span>
                <span>상황</span>
                <span>장소</span>
                <span>장르</span>
              </div>
              <div class="select-buttons">
                <form id="form1">
                  <div class="select-options" id="group1">
                    <div class="option-wrapper">
                      <span>최소</span>
                      <input type="text"  name="min_num_ppl" required/>
                      <span>명</span>
                    </div>
                    <div class="option-wrapper">
                      <span>최대</span>
                      <input type="text" name="max_num_ppl"/>
                      <span>명</span>
                    </div>
                  </div>

                  <div class="select-options" id="group2">
                    <div class="option-wrapper">
                      <span>최소</span>
                      <input type="text" name="min_time" />
                      <span>분</span>
                    </div>
                    <div class="option-wrapper">
                      <span>최대</span>
                      <input type="text"  name="max_time" />
                      <span>분</span>
                    </div>
                  </div>
                </form>

                <div class="select-options" id="group3">
                  <button class="option selected" value="전체">전체</button>
                  <button class="option" value="MT">MT</button>
                  <button class="option" value="술게임">술게임</button>
                  <button class="option" value="기타">기타</button>
                </div>

                <div class="select-options" id="group4">
                  <button class="option selected" value="전체">전체</button>
                  <button class="option" value="실내">실내</button>
                  <button class="option" value="야외">야외</button>
                  <button class="option" value="온라인">온라인</button>
                </div>

                <div class="select-options" id="group5">
                  <button class="option selected" value="전체">전체</button>
                  <button class="option" value="퀴즈">퀴즈</button>
                  <button class="option" value="순발력">순발력</button>
                  <button class="option" value="두뇌게임">두뇌게임</button>
                </div>


              </div>
            </div>
          </div>
          <div class="sec2">
            <h2>게임 소개</h2>
            <form id="gameForm" action="{% url 'game:create' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <span>게임명</span>
              <input type="text" name="title" />
              <span>진행준비</span>
              <textarea name="preparation" id="" cols="30" rows="2"></textarea>
              <span>게임 방법</span>
              <textarea name="explanation" id="" cols="30" rows="3"></textarea>
              <span>진행 팁 / 주의사항</span>
              <textarea name="tip" id="" cols="30" rows="5"></textarea>
              <span>썸네일 이미지</span>
              <div class="filebox">
                <input class="upload-name" value="첨부파일" placeholder="첨부파일"/>
                <label for="file">파일찾기</label>
                <input type="file" id="file" name="image"/>
                <button type="button" id="cancelFile">첨부 취소</button>
              </div>
              <input type="hidden" id="situation" name="situation_str">
              <input type="hidden" id="place" name="place_str">
              <input type="hidden" id="game_type" name="game_type_str">
              <div class="buttons">
                <input type="reset" value="취소하기!" id="cancel" />
                <input type="submit" value="등록하기!" id="submit" />
              </div>
            </form>
          </div>
      </div>

    <script src="{% static 'script/add_game.js'%}?after"></script>

    {% else %}
      <a href="{%url 'account:login'%}">
          <p>로그인을 해주세요</p>
      </a>
    {% endif %}

{% endblock %}

game/templates/game/delete.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <div style="text-align:center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Delete Article : {{ target_game.title }}</h4>
        </div>
        <form action="{% url 'game:delete' pk=target_game.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-danger round-pill col-6 mt-3">
        </form>

    </div>

{% endblock %}

game/templates/game/detail.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/more_game.css' %}?after" />
{% endblock %}
{% block content %}

    <div class="container">
      <div class="sec1">
        <div class="sec1-wrapper">
          <h1>{{target_game.title}}</h1>
          <div class="user-info">
            <span>{{target_game.author.nickname}}</span>
            <span>{{target_game.created_at | date:'Y.m.d' }}</span>
          </div>
          <div class="thumbnail-wrapper">
            {% if target_game.image %}
              <img src="{{ target_game.image.url }}" alt="">
            {% else %}
              <img src="{% static 'img/title.png' %}" alt="썸네일">
            {% endif %}
          </div>
          <ul class="game-info">
            <li>
              <span>인원</span>
              <p>{{ target_game.min_num_ppl}}명-{{ target_game.max_num_ppl}}명</p>
            </li>
            <li>
              <span>시간</span>
              <p>{{ target_game.min_time }}분-{{ target_game.max_time }}분</p>
            </li>
            <li>
              <span>상황</span>
              <p>{{ target_game.situation }}</p>
            </li>
            <li>
              <span>장소</span>
              <p>{{ target_game.place }}</p>
            </li>
            <li>
              <span>유형</span>
              <p>{{ target_game.game_type.all | join:", " }}</p>
            </li>
          </ul>
          <div class="buttons">
            <button id="like-button" data-game-id="{{ target_game.pk }}" data-liked="{{ is_like }}">
              {% if is_like %}
              <img src="{% static 'img/likefull.png' %}" alt="좋아요" /><span id="like-count">{{ target_game.likes.count }}</span>
              {% else %}
              <img src="{% static 'img/like.png' %}" alt="좋아요" /><span id="like-count">{{ target_game.likes.count }}</span>
              {% endif %}
            </button>
            <button class="playlist-button" onclick="openModal()">
              <img src="{% static 'img/folder.png' %}" alt="담기" /> 담기
            </button>
          </div>

        </div>
      </div>

      <div class="sec2">
        <div class="sec2-wrapper">
          <div class="about-game">
            <h3>게임 준비</h3>
            <p>{{target_game.preparation}}</p>
            <h3>게임 방법</h3>
            <p>{{target_game.explanation}}</p>
            <h3>진행 팁</h3>
            <p>{{target_game.tip}}</p>
          </div>
          {% if user.is_authenticated and user == target_game.author %}
          <div class="post-buttons">
            <button onclick="updatePost()"><img src="{% static 'img/fix.png' %}" alt="수정"/>수정</button>
            <button class="delete-button" onclick="deletePost()">
              <img src="{% static 'img/trash.png' %}" alt="삭제" />삭제
            </button>
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    <div id="myModal" class="modal">
      <div class="modal-content">
        <span onclick="closeModal()" class="close"
          ><img src="{% static 'img/close.png' %}" alt="닫기"
        /></span>
        <div class="modal-title">PlayList 선택</div>
        <ul>
          {% if user.is_authenticated %}
            {% if gameplaylists %}
              {% for gameplaylist in gameplaylists %}
              <li>
                <span id="playlist1">{{gameplaylist.title}}</span>
                <button class="collect-button" data-game-id="{{ target_game.pk }}" data-gameplaylist-id ="{{ gameplaylist.pk }}"
                 data-collected ={% if not gameplaylist in checked_gameplaylists %}
                                  "선택"
                                  {% else %}
                                  "취소"
                                  {% endif %} ></button>
              </li>

              {% endfor %}
            {% else %}
            <p style="text-align:center;">플레이리스트가 없습니다</p>
            {% endif %}
          {% else %}
            <p>로그인해주세요</p>
          {% endif %}
        </ul>
        <div class="modal-button">
          <a href="{% url 'gameplaylist:list'%}">PlayList 추가하기</a>
          <div class="finish-button">
            <button onclick="closeModal()">완료</button>
          </div>
        </div>
      </div>
    </div>

<hr>
  <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
  <script>
  $(document).ready(function() {

    // 페이지 로드 시 게임 플레이리스트 버튼 색깔 변경
     $('.collect-button').each(function() {
        var collected = $(this).data('collected');
        $(this).text(collected);
        if (collected == '선택') {
            $(this).css('background-color', 'rgba(187, 215, 184, 1)');
        } else {
            $(this).css('background-color', 'rgba(122, 159, 118, 1)');
        }
     });

    // 좋아요 클릭 시
    $("#like-button").on("click", function() {
      var game_id = $(this).data("game-id");
      var liked = $(this).data("liked");

      var $likeButton = $("#like-button");
      var $likeImage = $likeButton.find("img");

      $.ajax({
        type: "POST",
        url: "{% url 'game:like' %}",
        data: {
          'game_id': game_id,
          'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        success: function(response) {
          if (response.success) {
            $likeImage.attr("src", response.liked ? "{% static 'img/likefull.png' %}" : "{% static 'img/like.png' %}");
            $("#like-count").text(response.like_count);
            $("#like-button").data("liked", !liked);
          } else {
            alert(response.error);
          }
        },
        error: function() {
          alert("오류가 발생했습니다.");
        }
      });
    });
  });

  // 수정 클릭 시
  function updatePost() {
      window.location.href = "{% url 'game:update' pk=target_game.pk %}";
  }

  // 삭제 클릭 시
  function deletePost() {
    if (confirm("게시글을 삭제하시겠습니까??") == true) {
      window.location.href = "{% url 'game:delete' pk=target_game.pk %}";
    } else {
      //취소
      return false;
    }
  }

  // 담기 버튼 클릭 시
  function openModal() {
    {% if not user.is_authenticated %}
    alert("로그인을 해주세요");
    {% else %}
    var modal = document.getElementById("myModal");
    modal.style.display = "flex"; // 모달 표시
    {% endif %}
  }

  function closeModal() {
    var modal = document.getElementById("myModal");
    modal.style.display = "none"; // Hide the modal
  }

  // 플레이 리스트 선택/취소 클릭 시
  $(document).ready(function() {
    $(".collect-button").on("click", function() {
      var button = $(this);  // 클릭된 버튼을 변수에 저장
      var game_id = button.data("game-id");
      var gameplaylist_id = button.data("gameplaylist-id");
      $.ajax({
        type: "POST",
        url: "{% url 'gameplaylist:add_or_remove_game' %}",
        dataType: 'json',
        data: {
          'game_id': game_id,
          'gameplaylist_id': gameplaylist_id,
          'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        success: function(response) {
            var buttonText = response.collected ? "취소" : "선택";
            button.text(buttonText);
            var buttonColor = response.collected ? "rgba(122, 159, 118, 1)" : "rgba(187, 215, 184, 1)";
            button.css("background-color", buttonColor);
        },
        error: function(xhr, status, error) {
            console.error(xhr.responseText);
            alert("오류가 발생했습니다.");
        }
      });
    });
  });

  </script>

{% endblock %}

game/templates/game/like.html
<!-- 좋아요 기능 -->
<button id="like-button" data-game-id="{{ target_game.pk }}" data-liked="{{ is_like }}">
    {% if is_like %}
    취소
    {% else %}
    좋아요
    {% endif%}
</button>
<span id="like-count">{{ target_game.likes.count }}</span>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
      <script>
        $(document).ready(function() {
          $("#like-button").on("click", function() {
            var game_id = $(this).data("game-id");
            var liked = $(this).data("liked");

            $.ajax({
              type: "POST",
              url: "{% url 'game:like' %}",
              data: {
                'game_id': game_id,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
              },
              success: function(response) {
                if (response.success) {
                  if (response.liked) {
                    $("#like-button").text("취소");
                  } else {
                    $("#like-button").text("좋아요");
                  }
                  $("#like-count").text(response.like_count);
                  $("#like-button").data("liked", !liked);
                } else {
                  alert(response.error);
                }
              },
              error: function() {
                alert("오류가 발생했습니다.");
              }
            });
          });
        });
      </script>

game/templates/game/update.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/add_game.css' %}?after" />
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
      <div class="container">
          <div class="sec1">
            <h2>게임 특징</h2>
            <div class="background">
              <div class="select-name">
                <span>참여 인원</span>
                <span>소요 시간</span>
                <span>상황</span>
                <span>장소</span>
                <span>장르</span>
              </div>
              <div class="select-buttons">
                <form id="form1">
                  <div class="select-options" id="group1">
                    <div class="option-wrapper">
                      <span>최소</span>
                      <input type="text"  name="min_num_ppl" value="{{ form.min_num_ppl.value|default_if_none:'' }}"/>
                      <span>명</span>
                    </div>
                    <div class="option-wrapper">
                      <span>최대</span>
                      <input type="text" name="max_num_ppl" value="{{ form.max_num_ppl.value|default_if_none:'' }}"/>
                      <span>명</span>
                    </div>
                  </div>

                  <div class="select-options" id="group2">
                    <div class="option-wrapper">
                      <span>최소</span>
                      <input type="text" name="min_time"  value="{{ form.min_time.value|default_if_none:'' }}" />
                      <span>분</span>
                    </div>
                    <div class="option-wrapper">
                      <span>최대</span>
                      <input type="text"  name="max_time" value="{{ form.max_time.value|default_if_none:'' }}"/>
                      <span>분</span>
                    </div>
                  </div>
                </form>

                <div class="select-options" id="group3">
                  <button class="option" value="전체">전체</button>
                  <button class="option" value="MT">MT</button>
                  <button class="option" value="술게임">술게임</button>
                  <button class="option" value="기타">기타</button>
                </div>

                <div class="select-options" id="group4">
                  <button class="option" value="전체">전체</button>
                  <button class="option" value="실내">실내</button>
                  <button class="option" value="야외">야외</button>
                  <button class="option" value="온라인">온라인</button>
                </div>

                <div class="select-options" id="group5">
                  <button class="option" value="전체">전체</button>
                  <button class="option" value="퀴즈">퀴즈</button>
                  <button class="option" value="순발력">순발력</button>
                  <button class="option" value="두뇌게임">두뇌게임</button>
                </div>


              </div>
            </div>
          </div>
          <div class="sec2">
            <h2>게임 소개</h2>
            <form id="gameForm" action="{% url 'game:update' pk=target_game.pk %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <span>게임명</span>
              <input type="text" name="title" value="{{ form.title.value|default_if_none:'' }}" />
              <span>진행준비</span>
              <textarea name="preparation" id="" cols="30" rows="3">{{ form.preparation.value|default_if_none:'' }}</textarea>
              <span>게임 방법</span>
              <textarea name="explanation" id="" cols="30" rows="4">{{ form.explanation.value|default_if_none:'' }}</textarea>
              <span>진행 팁 / 주의사항</span>
              <textarea name="tip" id="" cols="30" rows="5">{{ form.tip.value|default_if_none:'' }}</textarea>
              <span>썸네일 이미지</span>
              <div class="filebox">
                <input class="upload-name" value="{{ form.image.value|default_if_none:'' }}" placeholder="첨부파일"/>
                <label for="file">파일찾기</label>
                <input type="file" id="file" name="image"/>
                <button type="button" id="cancelFile">첨부 취소</button>
              </div>
              <input type="hidden" id="situation" name="situation_str">
              <input type="hidden" id="place" name="place_str">
              <input type="hidden" id="game_type" name="game_type_str">
              <div class="buttons">
                <input type="reset" value="취소하기!" id="cancel" />
                <input type="submit" value="수정하기!" id="submit" />
              </div>
            </form>
          </div>
      </div>

    <script src="{% static 'script/add_game.js'%}?after"></script>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
          var place_button = document.getElementById("group4").querySelector('button[value="{{ place }}"]');
          place_button.classList.toggle("selected", true);

          var situation_button = document.getElementById("group3").querySelector('button[value="{{ situation }}"]');
          situation_button.classList.toggle("selected", true);

          var game_type_button = document.getElementById("group5").querySelector('button[value="{{ game_type }}"]');
          game_type_button.classList.toggle("selected", true);
      });
    </script>

    {% else %}
    <a href="{%url 'account:login'%}">
        <p>로그인을 해주세요</p>
    </a>



    {% endif %}

{% endblock %}